[package]
name = "riscv"
version = "0.1.0"
authors = ["Jack Rickard <jack.rickard@metaswitch.com>"]
edition = "2018"
publish = ["metaswitch"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
